version: '3.1'

networks:
  nest_architecture:
    driver: bridge

services:
  app:
    depends_on:
      - redis
      - postgres
    container_name: nest_architecture
    restart: unless-stopped
    command: bash -c "npm run start:dev"
    env_file: ./.env
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '4000:4000'

    environment:
      DB_HOST: postgres
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_PORT: $DB_PORT
      AUTH_REDIS_URL: redis://default:nest_architecture@redis:6379
    stdin_open: true
    tty: true
    networks:
      - nest_architecture

  redis:
    container_name: nest_architecture_redis
    image: redis:latest
    restart: unless-stopped
    command: redis-server --appendonly yes
    hostname: redis
    expose:
      - 6379
    networks:
      - nest_architecture

  postgres:
    container_name: nest_architecture_postgres
    image: postgres
    ports:
      - '5442:$DB_PORT'
    env_file: ./.env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    networks:
      - nest_architecture
